#
# GitLab CI/CD Pipeline for deploying DreamHouse App on Salesforce DX
#
before_script:
 # Decrypt server key
 - openssl aes-256-cbc -d -md md5 -in assets/server.key.enc -out assets/server.key -k $SERVER_KEY_PASSWORD
 # Install jq
 - apt update && apt -y install jq
 # Setup SFDX environment variables
 - export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
 - export SFDX_AUTOUPDATE_DISABLE=false
 - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
 - export SFDX_DOMAIN_RETRY=300
 - export SFDX_DISABLE_APP_HUB=true
 - export SFDX_LOG_LEVEL=DEBUG
 - export ROOTDIR=force-app/main/default/
 - export TESTLEVEL=RunLocalTests
 - export SCRATCH_ORG_ALIAS=DreamHouse_Scratch
 - export PACKAGEVERSION=""
 # Install Salesforce CLI
 - mkdir sfdx
 - wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
 - "./sfdx/install"
 - export PATH=./sfdx/$(pwd):$PATH
 # Output CLI version and plug-in information
 - sfdx --version
 - sfdx plugins --core
stages:
 - code-testing
 - integration-testing
 - app-deploy
#
# Create Scratch Org for code testing -- Stage 1
#
code-testing:
 stage: code-testing
 only:
  refs:
    - merge_requests
  variables:
    - $CI_MR_TARGET_BRANCH == 'production'
  #variables:
  #  - $CI_COMMIT_REF_NAME == 'production'
 script:
 # Authenticate to the Dev Hub using the server key
 - sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile assets/server.key --username $SF_USERNAME --setdefaultdevhubusername --setalias HubOrg

